// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/elokanugrah/go-financing-btpns/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserFacilityLimitRepository is an autogenerated mock type for the UserFacilityLimitRepository type
type UserFacilityLimitRepository struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserFacilityLimitRepository) GetByID(ctx context.Context, id int64) (domain.UserFacilityLimit, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.UserFacilityLimit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.UserFacilityLimit, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.UserFacilityLimit); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.UserFacilityLimit)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserFacilityLimitRepository creates a new instance of UserFacilityLimitRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserFacilityLimitRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserFacilityLimitRepository {
	mock := &UserFacilityLimitRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
