// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/elokanugrah/go-financing-btpns/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserFacilityRepository is an autogenerated mock type for the UserFacilityRepository type
type UserFacilityRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, uf
func (_m *UserFacilityRepository) Create(ctx context.Context, uf *domain.UserFacility) error {
	ret := _m.Called(ctx, uf)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserFacility) error); ok {
		r0 = rf(ctx, uf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserFacilityRepository creates a new instance of UserFacilityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserFacilityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserFacilityRepository {
	mock := &UserFacilityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
