// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/elokanugrah/go-financing-btpns/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserFacilityDetailRepository is an autogenerated mock type for the UserFacilityDetailRepository type
type UserFacilityDetailRepository struct {
	mock.Mock
}

// BulkCreate provides a mock function with given fields: ctx, details
func (_m *UserFacilityDetailRepository) BulkCreate(ctx context.Context, details []domain.UserFacilityDetail) error {
	ret := _m.Called(ctx, details)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.UserFacilityDetail) error); ok {
		r0 = rf(ctx, details)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserFacilityDetailRepository creates a new instance of UserFacilityDetailRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserFacilityDetailRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserFacilityDetailRepository {
	mock := &UserFacilityDetailRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
